### PR TITLE
Add color options for Border Play and Mute

### PR DESCRIPTION
**Pull request by simotek**
Personally i've always wanted a different color for the > play indicator to make it easier to read, in my mind it made sense to do the - mute indicator at the same time. In the default configs these are still mapped to the same color as cursor and normal.

In adition someone on Discord was after the ability to change the dialog border so I added that while I was there.

This commit also cleans up some whitespace in the parts of the code and docs that it touched.

### CODE REVIEW

**Comment by simotek** [comment]
Sorry another one that's probably best read with whitespace changes off. Although I did less of that this time.

**Comment by djdiskmachine** [comment]
Feel free to suggest changes to .clang-format, I feel that particularly this change looks nicer with your formatting than the suggestion
-GUIColor AppWindow::borderColor_    (0xFF,0x00,0x8C);
+GUIColor AppWindow::borderColor_(0xFF, 0x00, 0x8C);

**Comment by simotek** [comment]
> Feel free to suggest changes to .clang-format, I feel that particularly this change looks nicer with your formatting than the suggestion -GUIColor AppWindow::borderColor_ (0xFF,0x00,0x8C); +GUIColor AppWindow::borderColor_(0xFF, 0x00, 0x8C);

This is my preferred as well, I just fixed the stuff that really annoyed me and left stuff like that as it already was, I only automated the whitespace rather then going through with clangformat properly.

I'll go through and rebase my patches tomorrow.

**Comment by simotek** [comment]
Clang format is done, I also ran it on the header files that go with the .cpp files so there may be some headers with only formatting changes.

**Pull request merged**
