### PR TITLE
RG35XX+ support

### PR DESCRIPTION
**Pull request by igavrilov**
I tried the RG35XX OG build on my RG35XX+ console but wasn't able to run it due to the issue described in [this Reddit comment](https://www.reddit.com/r/RG35XX/comments/1af8tpu/comment/lc2vvxo/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button). It seems that the toolchain for the OG version is not compatible with the Plus version.

So, I built the app using the [union-rg35xxplus-toolchain](https://github.com/shauninman/union-rg35xxplus-toolchain), and it works well so far. Special thanks to @emartinez-dev for publishing his solution. I made a few changes:

- Switched the toolchain (the build with union-rg35xx-toolchain works, but it stutters after some time)
- Renamed "H" to "PLUS"
- Added a muOS shell script and a how-to guide

### CODE REVIEW

**Comment by djdiskmachine** [comment]
Thanks for the contribution and the descriptive solution!
I'll have another look at this this evening. =)

**Comment by djdiskmachine** [comment]
Hello! Sorry for the delayed response.
I've reviewed your changes and how they relate  to the following PR:
https://github.com/djdiskmachine/LittleGPTracker/pull/95

I will prioritize the changes in the Makefiles from pull 95 and your documentation and resource contributions.
I hope you find this fair. :)
Great job! Thanks a lot for helping to keep Little Piggy Tracker stay relevant! =3

**Comment by igavrilov** [comment]
Hey! It's absolutely fair, anyway I will respect your any decision since you're the maintainer :)
Looked at the #95, didn't expect plush file there.

---
There is definitely a problem with the build on RG35XX plus device as I explained [here](https://github.com/emartinez-dev/LittleGPTracker-rg35xx-plus/pull/1#issuecomment-2284800947). With higher BPMs (175 and above) it starts stuttering, however it works totally fine at 128-ish (which is **way more** better in comparison to RPi builds). I don't see this problem with my pocketCHIP device at all so it must be something specific to Anbernic. Unfortunately I don't own other devices so I can not test on H/S/24/OG this behaviour. When I find some spare time I'll try to build #95 to check if the issue still persist, otherwise I'll try to debug, it may take some time though. I'll keep you posted.

**Comment by simotek** [comment]
@djdiskmachine I'm in the process of merging this into #95 how do you feel about using `GARLICPLUS` for the naming of this one and `GARLIC` for what is currently `RG35XX`? Then using `RG35XX` and `RG35XXPLUS` for the images designed for the Stock OS?

Both GARLIC versions require SDL1.2 where as the Stock OS requires SDL2, The rg35xx-plus stock image is now also 64bit (aarch64-linux-gnu) while the rg35xx uses 32bit (arm-linux-gnueabihf). If we build with the right compile options then we probably shouldn't need separate builds for GARLIC and GARLICPLUS as the OS should be very similar if not the same, unless some compiler optimizations make a significant difference.

From talking to people on the rg35xx-plus discord I suspect that most rg35xx-plus/h users will wind up on the Stock or a Customized Stock Rom because the performance is better, similarly i'm not going to try and build a image for the stock os on the rg35xx unless someone is willing to test it, so we might be able to drop back to 2 images at some point.

**Comment by djdiskmachine** [comment]
> @djdiskmachine I'm in the process of merging this into #95 how do you feel about using `GARLICPLUS` for the naming of this one and `GARLIC` for what is currently `RG35XX`? Then using `RG35XX` and `RG35XXPLUS` for the images designed for the Stock OS?

I think this is a good idea!
Just add a line about it in the build readme :)

**Comment by purelygrey** [comment]
Hey, just my two cents, Garlic is not really a thing on all of the H700-based devices, so I find the naming pretty confusing, I'd call anything H700 related H700, since there are also 28XX and 40XX devices in the lineup now. MuOS calls their builds 35XX-SPLUSH, but there's also a RG40XX **V** device now, annoying. I'd rather just have H700 if there's no need for specific patches for 28xx and whatnot

I guess that doesn't really matter but I personally find stock firmware just about awful and I never use it :-D

**Comment by djdiskmachine** [comment]
Included in https://github.com/djdiskmachine/LittleGPTracker/pull/95

**Pull request closed without merging**
